### ISSUE TITLE
Create new type for Works

### ISSUE THREAD

**Issue by sohkai** [COALAIP/specs#3]
Right now, we have some hand-wavy methods of differentiating between a `Work` and a `Manifestation`. This could be simplified if we subtype `schema:CreativeWork` with something like `coala:AbstractWork` and enforce that all `Work`s use this type. `Work`s right now are always `schema:CreativeWork` anyway.

Would require some changes to pycoalaip.

Thoughts @TimDaub?

**Comment by TimDaub** [comment]
> his could be simplified if we subtype schema:CreativeWork with something like coala:AbstractWork and enforce that all Works use this type.

OK, but what's the exact benefit from subclassing?

**Comment by sohkai** [comment]
Avoiding having

> hand-wavy methods of differentiating between a `Work` and a `Manifestation`

in implementations. The current implementation is also kind of ugly, since it forces us to tack on some additional properties to assert that it is in fact a `Manifestation` and not a `Work` (`isManifestation`) when we already enforce `Work`s to be a specific type.

**Comment by TimDaub** [comment]
> since it forces us to tack on some additional properties to assert that it is in fact a Manifestation and not a Work (isManifestation) when we already enforce Works to be a specific type.

Makes sense! Go for it :+1:
